export const AUTH_TYPES = {
  AUTHORIZE: 'AUTHORIZE',
  AUTHORIZE_SUCCESS: 'AUTHORIZE_SUCCESS',
  AUTHORIZE_FAILURE: 'AUTHORIZE_FAILURE',

  LOGOUT: 'LOGOUT',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_ERROR: 'LOGOUT_ERROR',
  LOGOUT_CLEAN: 'LOGOUT_CLEAN',
};
