export const STORE_TYPES = {
  SEARCH: 'SEARCH_STORE',
  SEARCH_SUCCESS: 'SEARCH_STORE_SUCCESS',
  SEARCH_FAILURE: 'SEARCH_STORE_FAILURE',
  SEARCH_CLEAN: 'SEARCH_STORE_CLEAN',

  GET_STORE_DETAIL: 'GET_STORE_DETAIL',
  GET_STORE_DETAIL_SUCCESS: 'GET_STORE_DETAIL_SUCCESS',
  GET_STORE_DETAIL_FAILURE: 'GET_STORE_DETAIL_FAILURE',
  GET_STORE_DETAIL_CLEAN: 'GET_STORE_DETAIL_CLEAN',
};
