export const ImageSource = {
  Background: require('./Background.jpg'),
  Logo: require('./Logo.png'),
  EyeOpen: require('./EyeOpen.png'),
  EyeClose: require('./EyeClose.png'),
  SuccessCircle: require('./SuccessCircle.png'),
  DefaultCircle: require('./DefaultCircle.png'),
  Close: require('./Close.png'),
  CloseRed: require('./CloseRed.png'),
  ForgotPassCover: require('./ForgotPassCover.png'),
  Success: require('./Success.png'),
  ProfileAvatar: require('./ProfileAvatar.png'),
  Pen: require('./Pen.png'),
  ArrowDown: require('./ArrowDown.png'),
  ArrowLeft: require('./ArrowLeft.png'),
  Calendar: require('./Calendar.png'),
  Check: require('./Check.png'),
  Account: require('./Account.png'),
  Appointment: require('./Appointment.png'),
  Message: require('./Message.png'),
  TargetLocation: require('./TargetLocation.png'),
  Transaction: require('./Transaction.png'),
  Settings: require('./Settings.png'),
  Export: require('./Export.png'),
  Clock: require('./Clock.png'),
  Search: require('./Search.png'),
};
