export const USER_TYPES = {
  UPDATE_USER: 'UPDATE_USER',
  USER_SIGN_IN: 'USER_SIGN_IN',
  USER_SIGN_IN_SUCCESS: 'USER_SIGN_IN_SUCCESS',
  USER_SIGN_IN_FAILURE: 'USER_SIGN_IN_FAILURE',
  USER_SIGN_IN_CLEAN: 'USER_SIGN_IN_CLEAN',

  USER_SIGN_UP: 'USER_SIGN_UP',
  USER_SIGN_UP_SUCCESS: 'USER_SIGN_UP_SUCCESS',
  USER_SIGN_UP_FAILURE: 'USER_SIGN_UP_FAILURE',
  USER_SIGN_UP_CLEAN: 'USER_SIGN_UP_CLEAN',

  USER_REQUEST_OTP: 'USER_REQUEST_OTP',
  USER_REQUEST_OTP_SUCCESS: 'USER_REQUEST_OTP_SUCCESS',
  USER_REQUEST_OTP_FAILURE: 'USER_REQUEST_OTP_FAILURE',
  USER_REQUEST_OTP_CLEAN: 'USER_REQUEST_OTP_CLEAN',

  USER_RESET_PASSWORD: 'USER_RESET_PASSWORD',
  USER_RESET_PASSWORD_SUCCESS: 'USER_RESET_PASSWORD_SUCCESS',
  USER_RESET_PASSWORD_FAILURE: 'USER_RESET_PASSWORD_FAILURE',
  USER_RESET_PASSWORD_CLEAN: 'USER_RESET_PASSWORD_CLEAN',

  USER_UPDATE_PROFILE: 'USER_UPDATE_PROFILE',
  USER_UPDATE_PROFILE_SUCCESS: 'USER_UPDATE_PROFILE_SUCCESS',
  USER_UPDATE_PROFILE_FAILURE: 'USER_UPDATE_PROFILE_FAILURE',
  USER_UPDATE_PROFILE_CLEAN: 'USER_UPDATE_PROFILE_CLEAN',

  USER_UPDATE_AVATAR: 'USER_UPDATE_AVATAR',
  USER_UPDATE_AVATAR_SUCCESS: 'USER_UPDATE_AVATAR_SUCCESS',
  USER_UPDATE_AVATAR_FAILURE: 'USER_UPDATE_AVATAR_FAILURE',
  USER_UPDATE_AVATAR_CLEAN: 'USER_UPDATE_AVATAR_CLEAN',
};
